### ISSUE TITLE
error: no-assigning-return-values - eslint error (Do not assign the return value of a Cypress command))

### ISSUE THREAD

**Issue by anca0** [cypress-io/eslint-plugin-cypress#110]
I just added the eslint-plugin-cypress, now the linter is running against some of my tests.

There are some examples I have in the docs that are erroring in the eslint-plugin, which I thought should not be erroring since they are recommended uses of cypress. 
https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Return-Values

Can we make something to exclude this rule?

error cypress/no-assigning-return-values: Do not assign the return value of a Cypress command.

**Comment by MikeMcC399** [comment]
@anca0 

This is an old issue which was not responded to when you submitted it a long time ago. If I understood you correctly, you were looking for a way to disable the rule [no-assigning-return-values](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-assigning-return-values.md).

You can find instructions in [Disable rules](https://github.com/cypress-io/eslint-plugin-cypress#disable-rules) to do this.
