### ISSUE TITLE
Move to Core Cypress repo

### ISSUE THREAD

**Issue by jaffrepaul** [cypress-io/eslint-plugin-cypress#114]
In an effort to better maintain and enhance this official plugin, we will be moving it into the [main Cypress repo](https://github.com/cypress-io/cypress) sometime in the next few weeks. During that time, we will be going through issues and PRs to make sure all relevant items are moved over and labeled appropriately.

Once it is moved, this repo will be archived and will become read-only.

**Comment by ChrisCrossCrash** [comment]
Did this ever happen? I didn't see anything about it in this projects README and I couldn't find it on the main Cypress repo.

**Comment by jaffrepaul** [comment]
> Did this ever happen? I didn't see anything about it in this projects README and I couldn't find it on the main Cypress repo.

Hey @ChrisCrossCrash we started this process but are pausing while some other foundational changes take place in the core Cypress repo. The goal is still to make this happen but it will likely be part of a larger move to maintain Cypress plugins. Stay tuned!

**Comment by ChrisCrossCrash** [comment]
@jaffrepaul thanks for the update!

**Comment by Alco4998** [comment]
Hey, just wondering if there has been any progress made on this at the moment?

**Comment by jaffrepaul** [comment]
An issue has been added to the core Cypress repo to handle this. At this point it hasn't been prioritized relative to other work. You can keep an eye on the issue for new information. cc @nagash77 

https://github.com/cypress-io/cypress/issues/24251

**Comment by MikeMcC399** [comment]
@jaffrepaul 

- Has this plan been ditched or is there any likelihood that https://github.com/cypress-io/cypress/issues/24251 will be addressed?

**Comment by jennifer-shehane** [comment]
Yes, we don't intend to move this repo to the cypress repo. We'd prefer to keep it here.

**Comment by MikeMcC399** [comment]
@jennifer-shehane

> Yes, we don't intend to move this repo to the cypress repo. We'd prefer to keep it here.

That looks like a good decision. It is much easier to maintain as a stand-alone repo.
