### ISSUE TITLE
Node 16 with Mac OSX Ventura is failing with eslint deps

### ISSUE THREAD

**Issue by pmerwin** [cypress-io/eslint-plugin-cypress#120]
npm i eslint-plugin-cypress@latest --save-dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: lib-cypress-10@1.0.0
npm ERR! Found: eslint@4.19.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^4.19.1" from the root project
npm ERR!   peer eslint@">= 3.2.1" from @cypress/eslint-plugin-dev@5.3.2
npm ERR!   node_modules/@cypress/eslint-plugin-dev
npm ERR!     dev @cypress/eslint-plugin-dev@"5.3.2" from the root project

if I use node vs 14 it works.  Not sure how to solve ?

**Comment by MikeMcC399** [comment]
This is a stale issue and in the meantime Node.js `14` and `16` have both reached end-of-life and are no longer supported.

This repo is configured with `"@cypress/eslint-plugin-dev": "3.2.0"` there would have been a conflict if `@cypress/eslint-plugin-dev@5.3.2` was additionally installed.
