### ISSUE TITLE
cypress/unsafe-to-chain-command errors being throw for wait with alias (v2.13.1)

### ISSUE THREAD

**Issue by tgdevereux** [cypress-io/eslint-plugin-cypress#127]
With the latest version of eslint-plugin-cypress, version 2.13.1, cypress/unsafe-to-chain-command lint errors appear to be getting thrown for wait commands that chain commands from it, when wait is given an alias argument.

Based on the Cypress docs [here](https://github.com/cypress-io/cypress-documentation/blob/main/docs/api/commands/wait.mdx), it is unsafe to chain further commands that rely on the subject after .wait(), when given a time argument. However, it doesn't say it is unsafe when given an alias argument, as that would be used to wait and return a response from a request, for use in the test. 

Based on the above, should the cypress/unsafe-to-chain-command not be getting applied to wait commands with alias arguments?

**Comment by patrickcate** [comment]
Running into this same issue with the `cy.wait` command and the new rule. 

https://docs.cypress.io/api/commands/wait even includes examples such as:

```js
// Example: assert status from cy.intercept() before proceeding
cy.wait('@alias').its('response.statusCode').should('eq', 200)
```
and

```js
cy.wait('@userPut').its('request.url').should('include', 'users')
```

**Comment by Erik-Outreach** [comment]
Here's a PR to solve the issue: https://github.com/cypress-io/eslint-plugin-cypress/pull/128

**Comment by nagash77** [comment]
I just merged that PR and the build should publish the latest shortly.  I am going to close this issue for the time being.  Please comment back if the latest version doesn't resolve your issue.

**Comment by patrickcate** [comment]
The PR and new release does fix the issue. Rather than not applying the rule to any `cy.wait` commands, however, it would be great if it was still applied to non-alias `cy.wait` commands.

**Comment by patrickcate** [comment]
@nagash77, done with: https://github.com/cypress-io/eslint-plugin-cypress/issues/131
