### ISSUE TITLE
Add support for eslint 4

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/eslint-plugin-cypress#14]
The new rules introduced in [2.1.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.1.0) only support eslint 5 and [cause errors in eslint 4](https://github.com/cypress-io/eslint-plugin-cypress/issues/11). Add backwards compatibility with eslint 4 so that the recommended rules can be used with it.

**Comment by maddhruv** [comment]
Raised a PR for `no-assigning-return-value` fix - https://github.com/cypress-io/eslint-plugin-cypress/pull/49, which also fixes all tests for `eslint@4.x.x`
