### ISSUE TITLE
cypress/no-pause is not working if the command is chained

### ISSUE THREAD

**Issue by TobiasHH** [cypress-io/eslint-plugin-cypress#147]
I using Intellij with eslint in my Project.

If I use pause as a parent command the linter works fine.

cy.pause();

If I use pause as a child command nothing is highlighted.

cy.get('p').pause();

**Comment by MikeMcC399** [comment]
Thanks for your comment @tom9744!

> It seems like this is an expected behavior because the document([docs/rules/no-pause.md](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-pause.md)) says usages like `cy.get("p").pause()` won't be detected.

I've changed the https://github.com/cypress-io/eslint-plugin-cypress/labels/bug label to https://github.com/cypress-io/eslint-plugin-cypress/labels/type%3A%20enhancement instead.

**Comment by tom9744** [comment]
Though I'm quite new to this project, I want to give it a shot and try resolving the issue. Could I work on it?

**Comment by jennifer-shehane** [comment]
@tom9744 Yes, PRs are welcome!
