### ISSUE TITLE
VSCode: Cannot read property 'recommended' of undefined

### ISSUE THREAD

**Issue by kaseymccurdy** [cypress-io/eslint-plugin-cypress#16]
I followed the install steps for this plugin as outlined in the readme. 

Upon adding `"plugin:cypress/recommended"` to the "extends" block of .eslintrc, i get the following error:

<img width="449" alt="screen shot 2019-01-21 at 2 23 48 pm" src="https://user-images.githubusercontent.com/45602551/51500006-b2dc0700-1d89-11e9-984b-8f145da1ce7a.png">

Digging deeper, i see:
<img width="1378" alt="screen shot 2019-01-21 at 2 27 55 pm" src="https://user-images.githubusercontent.com/45602551/51500009-b96a7e80-1d89-11e9-8705-cc08502d33af.png">

I'll gladly provide any additional info you may need...im out of ideas on where to dig...

Thanks!!

**Comment by chrisbreiding** [comment]
What happens if you run eslint from the command line? Does it fail the same way? Also, what version of eslint do you have installed?

**Comment by kaseymccurdy** [comment]
Everything runs just fine on the command line. we are using version 5, but I will have to get back to you with the exact version number...

**Comment by kaseymccurdy** [comment]
Our exact eslint version is 5.7.0.

In VSCode, im using this extension: https://github.com/Microsoft/vscode-eslint

Is there anything else that would be helpful?

**Comment by spencermefford** [comment]
+1

**Comment by RichieMerchant** [comment]
Did this ever get resolved? I'm getting the same issue now in Jan 2020 after following the recommended configuration https://github.com/cypress-io/eslint-plugin-cypress#recommended-configuration.

**Comment by MikeMcC399** [comment]
Closing as stale issue.
