### ISSUE TITLE
How to override rules?

### ISSUE THREAD

**Issue by lolpez** [cypress-io/eslint-plugin-cypress#19]
I can't override the rules for this plugin, I want to use double brackets instead of one, I used this:
```
"rules": {
        "cypress/cypress": ["error", { "singleQuote": true }]
}
```

Any suggestions?

**Comment by chrisbreiding** [comment]
This plugin only has [3 rules](https://github.com/cypress-io/eslint-plugin-cypress#rules) and does not specify any others when you extend with "cypress/recommended". I think there must be another rule or plugin you need to override.
