### ISSUE TITLE
cypress/no-async-before rule documentation issues

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/eslint-plugin-cypress#193]
- This issue follows on from issue https://github.com/cypress-io/eslint-plugin-cypress/issues/190

## Issue

- The rule [no-async-before](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-before.md) provided by PR https://github.com/cypress-io/eslint-plugin-cypress/pull/151 has some associated documentation errors and omissions:

1. The entry for this rule is missing in the [README > Rules](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/README.md#rules) section, although it is mentioned in the [README > Usage](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/README.md#usage) section.
2. The documentation heading for [no-async-before](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-before.md) "Prevent using async/await in Cypress test cases (no-async-tests)" is incorrect and is the same as [no-async-tests](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-async-test.md).

**Comment by MikeMcC399** [comment]
This issue is addressed in 2 PRs:

- #197 
- #198

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Can this be closed?

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Can this be closed?

Yes, now that both related PR have been merged. Thanks.
