### ISSUE TITLE
Add Rule: Error if `.only` is found in tests.

### ISSUE THREAD

**Issue by juliusdelta** [cypress-io/eslint-plugin-cypress#28]
We've had a few times where we commit a `.only` in the specs. I figured it could be a linting rule so it doesn't make it into a master branch for projects that have lint checks in their CI pipeline or GH actions.

I'm willing to add this myself if people think it's a good idea.

**Comment by chrisbreiding** [comment]
Please see this discussion: https://github.com/cypress-io/eslint-plugin-cypress/pull/25

**Comment by penx** [comment]
@chrisbreiding unfortunately the discussion in #25 didn't seem to result in anything, as far as I can see.

Can this issue be reopened?

In the meantime, for anyone else landing here, using https://www.npmjs.com/package/eslint-plugin-no-only-tests should suffice, as demonstrated in https://github.com/radicle-dev/radicle-upstream/pull/426
