### ISSUE TITLE
Show an errror when using arrow functions with hooks

### ISSUE THREAD

**Issue by Kocal** [cypress-io/eslint-plugin-cypress#31]
Hi, 

Today I've tried to use `this.skip()` inside `before()` `it()` but it didn't work because I was using arrow functions instead of _normal_ functions and so `this` was undefined.

It took me some time before being able to make `this.skip()` works, and I think creating a rule can save time from other people too.

This rule would be recommended and will throw an error when using arrow functions with :
- describe, context
- it, it.skip, it.only, ... specify
- before/beforeEach
- after/afterEach

What do you think? I can open a PR for this rule (I've never write an ESLint rule but it does not seems really complicated)

Thanks!

**Comment by chrisbreiding** [comment]
Instead of erroring always when you use an arrow function with `describe`, `it`, etc, I would rather it error only if you use an arrow function and then use `this` inside the function body.

Bonus points if it could auto-fix by converting the arrow function into a regular function in that case.

**Comment by Kocal** [comment]
Mmmmh indeed that's a better behavior. I will see what I can do.

**Comment by brettz9** [comment]
IMO, since this is general purpose functionality, it would be better to let users add an equivalent rule from `eslint-plugin-mocha` instead: https://github.com/lo1tuma/eslint-plugin-mocha/blob/1954cf3b3732d1cdb0e727791c806c5e341484a0/docs/rules/no-mocha-arrows.md . I think this plugin should be reserved for cypress-specific issues.

**Comment by chrisbreiding** [comment]
I agree with @brettz9. No need to to reinvent the wheel on this.

**Comment by Kocal** [comment]
Oh, I didn't know that rule. Thanks! :)

**Comment by brettz9** [comment]
Btw, FWIW, some other nice Mocha plugins:

1. https://github.com/lo1tuma/eslint-plugin-mocha/
1. https://github.com/onechiporenko/eslint-plugin-mocha-cleanup

And chai ones:

1. https://github.com/gavinaiken/eslint-plugin-chai-expect-keywords/
1. https://github.com/fintechstudios/eslint-plugin-chai-as-promised/
1. https://github.com/ihordiachenko/eslint-plugin-chai-friendly/ (mentioned in the README)
1. https://github.com/Turbo87/eslint-plugin-chai-expect
