### ISSUE TITLE
Add opinionated rules

### ISSUE THREAD

**Issue by jbinto** [cypress-io/eslint-plugin-cypress#4]
Would be cool if this plugin could do things like warn on calls to `.wait()`, and enforce other Cypress best practices.

**Comment by chrisbreiding** [comment]
That's a great idea. We've talked about in the past, just haven't taken the time to come up with the exact rules and implement them. I'll keep this open to track any progress we make.

**Comment by MikeMcC399** [comment]
This suggestion is implemented.

See 

- [Recommended configuration](https://github.com/cypress-io/eslint-plugin-cypress#recommended-configuration) and
- [No Unnecessary Waiting](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/no-unnecessary-waiting.md)
