### ISSUE TITLE
Need a yarn installation support 

### ISSUE THREAD

**Issue by Ishaan28malik** [cypress-io/eslint-plugin-cypress#53]
I used ``` yarn add eslint-plugin-cypress --save-dev ``` 
But things are not working as every time I run this script It shows waiting or error.

Need an update for yarn support.

**Comment by Ishaan28malik** [comment]
Worked well for me later after a few tries.
Requires a good network connection.

**Comment by ogelacinyc** [comment]
Hi, I think document is need to fix a option `--save-dev` to `--dev` for yarn.
I use yarn 1.22.4
