### ISSUE TITLE
Rule suggestion: No chained Cypress commands

### ISSUE THREAD

**Issue by isaac-jordan** [cypress-io/eslint-plugin-cypress#55]
As mentioned in Cypress docs, [only the last command in a chain is retried](https://docs.cypress.io/guides/core-concepts/retry-ability.html#Only-the-last-command-is-retried).

This can lead to flaky tests that could be avoided by not chaining commands. I'd love to have this  as a rule in eslint-plugin-cypress, so that we can catch this usage of Cypress commands (doesn't necessarily need to be added to the recommended set).

**Comment by chrisbreiding** [comment]
It's true that only the last command before a failure is retried, but removing the chaining will not cause more than the last command to retry. The doc you linked goes into the solutions for that sort of flake better than I can summarize here. 

In any case, removing chaining won't help prevent test flake, so I don't think we should have a rule for it.

**Comment by isaac-jordan** [comment]
> removing the chaining will not cause more than the last command to retry

Why is that? Is it because retryability requires an assertion? If so, why would it not be a useful rule to require assertions between chained commands?

The best practice here seems to be "Don't have directly chained `.get` or `.contains` or `.find` (etc) commands without assertions in the middle".

**Comment by chrisbreiding** [comment]
It really depends on the app you're testing and the specifics of the test you're writing. That's why that doc lists 3 possible solutions for the example flaky test. Also, that doc describes a case where chaining query commands is problematic, but there are cases where doing so is perfectly fine.

**Comment by isaac-jordan** [comment]
All 3 of those solutions remove the chained commands. I'd love to be able to ward off these flaky tests with a rule so it doesn't come down to code reviews to spot potential flakiness when a blanket "Don't chain commands without assertions" would avoid the problem. 

I agree it might be a bit strong to have as a default recommended rule, but an optional one from this plugin would be awesome. 

I also agree there are some cases where chaining is fine (presumably why Cypress allows it at all), but that logic can apply to most eslint rules.

Would you be able to outline why you think it an inappropriate rule to have as an optional inclusion for users?

**Comment by chrisbreiding** [comment]
I'm hesitant to add it to this plugin for 2 reasons:

1. While it wouldn't be a 'recommended' rule, in eslint, 'recommended' really just means 'enabled by default'. By putting it in this plugin at all, we're somewhat recommending it.
2. Any rule added to this plugin increases the maintenance burden of this repo. We've had a number of rules added by external contributors. They looked good and passed review and were merged and published. They seemed like easy wins. But then issues come up as different users use them and find they don't work for particular use cases. It falls on me and other maintainers to manage, debug, and fix the issues, which takes time away from higher priorities.

I'd suggest creating a separate eslint plugin, something like `eslint-plugin-cypress-contrib`, and adding this rule there. We can put it on the [plugins page](https://docs.cypress.io/plugins/) of the docs. If the rule proves popular and robust through real-world usage over time, we can re-evaluate adding it to this plugin. It's something we do with the main Cypress repo. We often try out more experimental things separately as a plugin, iron out the kinks, and then work on integrating them into Cypress itself.
