### ISSUE TITLE
Errors when assigning cy.spy() return value

### ISSUE THREAD

**Issue by cbrunnkvist** [cypress-io/eslint-plugin-cypress#56]
Since `cypress/no-assigning-return-values` is enabled and in the "recommended" ruleset, we get

> `error  Do not assign the return value of a Cypress command`

for code that uses `cy.spy()` synchronously e.g.

`const nameSpy = cy.spy(user, 'setName')`

From [the docs](https://docs.cypress.io/api/commands/spy.html#Yields):

> Unlike most Cypress commands, cy.spy() is synchronous and returns a value (the spy) instead of a Promise-like chain-able object.

I believe there are at two possible options here: either allow the rule to exclude cy.spy assignments in particular, **or** update the docs to declare that using return value is deprecated in favor of aliasing + change the linter error message to include such a recommendation IF indeed works / it actually does return a chainable.

**Comment by jennifer-shehane** [comment]
We would be welcome to a PR for this.
