### ISSUE TITLE
scope.resolve is not a function when running eslint

### ISSUE THREAD

**Issue by alisd23** [cypress-io/eslint-plugin-cypress#69]
When I run `eslint` from the command line I get the following error:

```
scope.resolve is not a function
at isIdentifierNumberConstArgument (/home/ali/dev/planty/node_modules/eslint-plugin-cypress/lib/rules/no-unnecessary-waiting.js:59:36)
...
```

Looks like it's coming from the **no-unnecessary-waiting.js** rule. Is this plugin not compatible with eslint 7.8.1 currently?

Lib versions
- `eslint`: 7.8.1 
- `eslint-plugin-cypress`: 2.11.1

**Comment by kgabryje** [comment]
I have the same problem, would appreciate any help.

**Comment by ertrzyiks** [comment]
Do you guys use Typescript with `typescript-eslint` plugin? This problem started to happening once we updated typescript eslint plugin

**Comment by ertrzyiks** [comment]
I put together an example repo which is affected by this issue https://github.com/ertrzyiks/typescript-eslint-cypress-conflict and reported it to https://github.com/typescript-eslint/typescript-eslint/issues/2596

**Comment by ertrzyiks** [comment]
https://eslint.org/docs/developer-guide/scope-manager-interface#deprecated-members-2
scope.resolve is apparently deprecated and it's not a problem with typescript-eslint.
