### ISSUE TITLE
no-assigning-return-values: TypeError: Cannot read property 'callee' of undefined

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/eslint-plugin-cypress#8]
```
TypeError: Cannot read property 'callee' of undefined
  at isCypressCommandDeclaration (C:\git\test\node_modules\eslint-plugin-cypress\lib\rules\no-assigning-return-values.js:38:17)
  at Array.some (<anonymous>:null:null)
  at VariableDeclaration (C:\git\test\node_modules\eslint-plugin-cypress\lib\rules\no-assigning-return-values.js:24:31)
```
I'll try and make a PR if I can get to the bottom of it.

**Comment by chrisbreiding** [comment]
Version `2.1.1` has been published to NPM. The full release note can be found at [eslint-plugin-cypress/releases/tag/v2.1.1](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.1.1).

**Tip:** safely upgrade dependency eslint-plugin-cypress in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by randing89** [comment]
I am still getting this error in `2.1.1`

```
TypeError: Cannot read property 'callee' of undefined
at isCypressCommandDeclaration (/buildeng/bamboo-agent-home/xml-data/build-dir/CONFMICRO-CFN255-RLT/node_modules/eslint-plugin-cypress/lib/rules/no-assigning-return-values.js:41:17)
```

**Comment by chrisbreiding** [comment]
Version `2.1.2` has been published to NPM. The full release note can be found at [eslint-plugin-cypress/releases/tag/v2.1.2](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.1.2).

**Tip:** safely upgrade dependency eslint-plugin-cypress in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by HugoGresse** [comment]
I'm stil having this issue in the 2.7.0

**Comment by HugoGresse** [comment]
See https://github.com/HugoGresse/open-feedback/pull/167

**Comment by HugoGresse** [comment]
Shouldn't this be re-open?
