### ISSUE TITLE
Feature request: Disallow describe.only and it.only

### ISSUE THREAD

**Issue by jlherren** [cypress-io/eslint-plugin-cypress#87]
[According to the Cypress docs](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Excluding-and-Including-Tests), one recommended way to write tests is to temporarily use `describe.only` and/or `it.only` to only run the single test currently being written.

If I understand the concept correctly, these two functions are useful while writing tests, but should never be committed to version history. However, that happens way to easily by accident, if we forget to remove the `.only` part. I therefore propose a new rule to disallow these functions entirely. (`.skip` probably shouldn't be included here, as it makes sense to commit an incomplete test.)

**Comment by kyledetella** [comment]
@jlherren see https://github.com/cypress-io/eslint-plugin-cypress/issues/28 – it looks like this was discussed and there was a potential workaround.

**Comment by jlherren** [comment]
Thanks! So to sum up, it was considered a great idea, but somehow never happened. I'll give [eslint-plugin-no-only-tests](https://www.npmjs.com/package/eslint-plugin-no-only-tests) a try in the meantime.

**Comment by MikeMcC399** [comment]
This would duplicate the rule

https://github.com/lo1tuma/eslint-plugin-mocha/blob/main/docs/rules/no-exclusive-tests.md

https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.eslintrc shows an example of the two plugins working side-by-side to achieve the goal of flagging `describe.only` and `it.only`

- `eslint-plugin-mocha`
- `eslint-plugin-cypress`

See also the comments in

- PR https://github.com/cypress-io/eslint-plugin-cypress/pull/25

where it was decided not to duplicate the functionality from `eslint-plugin-mocha` and put it into `eslint-plugin-cypress`.
