### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [cypress-io/eslint-plugin-cypress#89]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by MikeMcC399** [comment]
- See also #175

**Comment by MikeMcC399** [comment]
- I've submitted PR #176 to officially declare support for ESLint `8.x`.  This would be a new major release as it drops support for earlier versions.
