### ISSUE TITLE
Plugin not working in cypress standalone project with Typescript

### ISSUE THREAD

**Issue by jprealini** [cypress-io/eslint-plugin-cypress#91]
I have a Cypress 9.0 standalone project (not included inside a main app project), using Typescript.
I followed the instructions to install the plugin
* npm install eslint -D
* npm install eslint-plugin-cypress -D
* create a .eslintrc.json in the cypress root folder with the following content
```
{
  "extends": [
    "plugin:cypress/recommended"
  ]
}
```
Restarted VSCode... but when I put a cy.wait(1000) in any test, it doesn't yell at me.. I even tried adding the rules to the json file as it indicated the documentation, but nothing

What am I missing? 

Thanks

**Comment by MikeMcC399** [comment]
This is a stale issue and it is not clear which version of `eslint-plugin-cypress` was installed.

The functionality is tested successfully in CI with https://github.com/cypress-io/eslint-plugin-cypress/blob/master/tests/lib/rules/no-unnecessary-waiting.js
