### ISSUE TITLE
Update CircleCI Node Docker Image

### ISSUE THREAD

**Issue by emilyrohrbough** [cypress-io/eslint-plugin-cypress#92]
Notice on https://circleci.com/docs/2.0/circleci-images/ reads:

> Legacy images with the prefix "circleci/" will be [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) on December 31, 2021. For faster builds, upgrade your projects with [next-generation convenience images](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/).

Update `.circle.yml` to use [`cimg/node`](https://hub.docker.com/r/cimg/node).

**Comment by MikeMcC399** [comment]
The CircleCI workflow [circle.yml](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/circle.yml) uses

```yml
      - image: circleci/node:16
```

which remains deprecated. Additionally in the meantime Node.js `16` transitioned on Sep 11, 2023 into end-of-life status and is no longer supported by Cypress. Apparently `circleci/node:16` is pegged to an earlier version of Node.js `16.x`. Starting with Node.js `v16.15.1`, a simple `npm ci` can no longer install dependencies. The `npm ci` / `npm install` option `--legacy-peer-deps` is required as a workaround.

## Related issues

- #158 
- #153 
- #157

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/eslint-plugin-cypress/pull/167 is proposed to solve dependency issues which should allow using Node.js `18`, `20` or `21`. This is turn should allow [cimg/node](https://circleci.com/developer/images/image/cimg/node) to be used, for instance `cimg/node:20.12.2`.
